name: Pipeline de Validação de Dados

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validar_dados:
    runs-on: ubuntu-latest
    
    steps:
    - name: Collect Workflow Telemetry
      uses: catchpoint/workflow-telemetry-action@v2
    
    - name: Pegar o código
      uses: actions/checkout@v3
      
    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Instalar pandas
      run: pip install pandas
      
    - name: Validar dados
      id: validacao
      run: python validar_dados.py